name: Auto Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://zfrqbl.com/
          drop-html-extension: true

      - name: Commit and Push Sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update sitemap.xml"
          file_pattern: sitemap.xml
